modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "bloom"
version = "${version}"
displayName = "Bloom"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.bloom]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloom]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bloom]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bloom.mixins.json"
